# coding: utf-8

"""
    Transaction Search

    Use the Transaction Search API to get the history of transactions for a PayPal account. To use the API on behalf of third parties, you must be part of the PayPal partner network. Reach out to your partner manager for the next steps. To enroll in the partner program, see <a href=\"https://www.paypal.com/my/webapps/mpp/partner-program/global-programs\">Partner with PayPal</a>. For more information about the API, see the <a href=\"/docs/transaction-search/\">Transaction Search API Integration Guide</a>.<blockquote><strong>Note:</strong> To use the API on behalf of third parties, you must be part of the PayPal partner network. Reach out to your partner manager for the next steps. To enroll in the partner program, see <a href=\"https://www.paypal.com/my/webapps/mpp/partner-program/global-programs\">Partner with PayPal</a>.</blockquote>

    The version of the OpenAPI document: 1.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.item_detail import ItemDetail
from typing import Optional, Set
from typing_extensions import Self

class CartInfo(BaseModel):
    """
    The cart information.
    """ # noqa: E501
    item_details: Optional[Annotated[List[ItemDetail], Field(min_length=1, max_length=32767)]] = Field(default=None, description="An array of item details.")
    tax_inclusive: Optional[StrictBool] = Field(default=False, description="Indicates whether the item amount or the shipping amount already includes tax.")
    paypal_invoice_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=127)]] = Field(default=None, description="The ID of the invoice. Appears for only PayPal-generated invoices.")
    __properties: ClassVar[List[str]] = ["item_details", "tax_inclusive", "paypal_invoice_id"]

    @field_validator('paypal_invoice_id')
    def paypal_invoice_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z0-9_\'\-., \":;\!?]*$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9_'\-., \":;\!?]*$/")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CartInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in item_details (list)
        _items = []
        if self.item_details:
            for _item in self.item_details:
                if _item:
                    _items.append(_item.to_dict())
            _dict['item_details'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CartInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "item_details": [ItemDetail.from_dict(_item) for _item in obj["item_details"]] if obj.get("item_details") is not None else None,
            "tax_inclusive": obj.get("tax_inclusive") if obj.get("tax_inclusive") is not None else False,
            "paypal_invoice_id": obj.get("paypal_invoice_id")
        })
        return _obj


