# coding: utf-8

"""
    Transaction Search

    Use the Transaction Search API to get the history of transactions for a PayPal account. To use the API on behalf of third parties, you must be part of the PayPal partner network. Reach out to your partner manager for the next steps. To enroll in the partner program, see <a href=\"https://www.paypal.com/my/webapps/mpp/partner-program/global-programs\">Partner with PayPal</a>. For more information about the API, see the <a href=\"/docs/transaction-search/\">Transaction Search API Integration Guide</a>.<blockquote><strong>Note:</strong> To use the API on behalf of third parties, you must be part of the PayPal partner network. Reach out to your partner manager for the next steps. To enroll in the partner program, see <a href=\"https://www.paypal.com/my/webapps/mpp/partner-program/global-programs\">Partner with PayPal</a>.</blockquote>

    The version of the OpenAPI document: 1.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.shipping_info import ShippingInfo

class TestShippingInfo(unittest.TestCase):
    """ShippingInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShippingInfo:
        """Test ShippingInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShippingInfo`
        """
        model = ShippingInfo()
        if include_optional:
            return ShippingInfo(
                name = '5''UOq1hlK5jZXw'V6.YZb0',
                method = '5''UOq1hlK5jZXw'V6.YZb0',
                address = openapi_client.models.simple_postal_address_(coarse_grained).Simple Postal Address (Coarse-Grained)(
                    line1 = '', 
                    line2 = '', 
                    city = '', 
                    state = '', 
                    country_code = 'C201', 
                    postal_code = '', ),
                secondary_shipping_address = openapi_client.models.simple_postal_address_(coarse_grained).Simple Postal Address (Coarse-Grained)(
                    line1 = '', 
                    line2 = '', 
                    city = '', 
                    state = '', 
                    country_code = 'C201', 
                    postal_code = '', )
            )
        else:
            return ShippingInfo(
        )
        """

    def testShippingInfo(self):
        """Test ShippingInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
