# coding: utf-8

"""
    Transaction Search

    Use the Transaction Search API to get the history of transactions for a PayPal account. To use the API on behalf of third parties, you must be part of the PayPal partner network. Reach out to your partner manager for the next steps. To enroll in the partner program, see <a href=\"https://www.paypal.com/my/webapps/mpp/partner-program/global-programs\">Partner with PayPal</a>. For more information about the API, see the <a href=\"/docs/transaction-search/\">Transaction Search API Integration Guide</a>.<blockquote><strong>Note:</strong> To use the API on behalf of third parties, you must be part of the PayPal partner network. Reach out to your partner manager for the next steps. To enroll in the partner program, see <a href=\"https://www.paypal.com/my/webapps/mpp/partner-program/global-programs\">Partner with PayPal</a>.</blockquote>

    The version of the OpenAPI document: 1.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payer_info import PayerInfo

class TestPayerInfo(unittest.TestCase):
    """PayerInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayerInfo:
        """Test PayerInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayerInfo`
        """
        model = PayerInfo()
        if include_optional:
            return PayerInfo(
                account_id = 'Cu2LC4aWwWL9Y864DZtaGR0',
                email_address = 'j@Z,rZ#UM/?R,Fp^l6$ARjbhJk C>i H'qT\\{<?'es#)#iK.YM{Rag2/!KB!k@5oXh.:Ts\";mG012',
                phone_number = openapi_client.models.phone.Phone(
                    country_code = '8070', 
                    national_number = '807288800150', 
                    extension_number = '8072888001528020', ),
                address_status = '|0',
                payer_status = '|0',
                payer_name = openapi_client.models.name.Name(
                    prefix = '', 
                    given_name = '', 
                    surname = '', 
                    middle_name = '', 
                    suffix = '', 
                    alternate_full_name = '', 
                    full_name = '', ),
                country_code = 'C201',
                address = openapi_client.models.simple_postal_address_(coarse_grained).Simple Postal Address (Coarse-Grained)(
                    line1 = '', 
                    line2 = '', 
                    city = '', 
                    state = '', 
                    country_code = 'C201', 
                    postal_code = '', )
            )
        else:
            return PayerInfo(
        )
        """

    def testPayerInfo(self):
        """Test PayerInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
